site_name: DuViews Documentation
site_url: https://rainboxlab.org
repo_url: https://github.com/Rainbox-dev/DuBLF_DuViews/
edit_uri: edit/master/src-docs/docs/
site_description: The DuViews comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2019 Rainbox Lab and Nicolas Dufresne'
theme:
    name: readthedocs
    custom_dir: theme/
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - codehilite
    - fenced_code
    - toc
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
nav:
    - DuViews: index.md
